# Generated by Django 2.2 on 2019-04-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=48)),
                ('main_category', models.CharField(max_length=48)),
                ('currency', models.CharField(max_length=12)),
                ('deadline', models.DateField()),
                ('goal', models.IntegerField()),
                ('launched', models.DateTimeField()),
                ('pledged', models.FloatField()),
                ('state', models.CharField(max_length=24)),
                ('backers', models.IntegerField()),
                ('country', models.CharField(max_length=12)),
                ('usd_pledged', models.FloatField()),
                ('usd_pledged_real', models.FloatField()),
                ('usd_goal_real', models.FloatField()),
            ],
        ),
    ]
